name: 💅 Feature Request
description: Submit a Feature Request, new API idea or game-play changes.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what your feature request is about. Please don't ask for too many things in a single issue, the chance they won't get done is higher as it's harder to maintain the track of them. Split it into several issues if needed.
    validations:
      required: true

  - type: textarea
    attributes:
      label: API Design
      description: |
        Please describe, if applicable, how this feature could be exposed in the Scripting API.
      placeholder: |
        Example: Character:SetHealth(new_health)

  - type: textarea
    attributes:
      label: Motivation
      description: Please outline the motivation for the proposal and why it should be implemented. Has this been requested by a lot of users?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: Please describe alternatives you've considered to achieve this result using the existing methods.
